schema_version = "1.0.0"

id = "ps1_decimator"
name = "PS1 Decimator"
version = "0.1.0"
type = "add-on"
tagline = "Stylized low-poly decimation + UV pixelation for PS1 aesthetics"
maintainer = "Hamada Gasmallah"

blender_version_min = "4.2.0"

license = ['SPDX:GPL-3.0-or-later']

# Optional but nice:
tags = ["Modeling", "Mesh"]
platforms = ["windows-x64"]

wheels = [
  "./wheels/asttokens-3.0.0-py3-none-any.whl",
  "./wheels/attrs-25.3.0-py3-none-any.whl",
  "./wheels/blinker-1.9.0-py3-none-any.whl",
  "./wheels/certifi-2025.8.3-py3-none-any.whl",
  "./wheels/charset_normalizer-3.4.3-cp311-cp311-win_amd64.whl",
  "./wheels/click-8.2.1-py3-none-any.whl",
  "./wheels/colorama-0.4.6-py2.py3-none-any.whl",
  "./wheels/comm-0.2.3-py3-none-any.whl",
  "./wheels/configargparse-1.7.1-py3-none-any.whl",
  "./wheels/dash-3.2.0-py3-none-any.whl",
  "./wheels/decorator-5.2.1-py3-none-any.whl",
  "./wheels/executing-2.2.0-py2.py3-none-any.whl",
  "./wheels/fastjsonschema-2.21.2-py3-none-any.whl",
  "./wheels/flask-3.1.2-py3-none-any.whl",
  "./wheels/idna-3.10-py3-none-any.whl",
  "./wheels/importlib_metadata-8.7.0-py3-none-any.whl",
  "./wheels/ipython-9.4.0-py3-none-any.whl",
  "./wheels/ipython_pygments_lexers-1.1.1-py3-none-any.whl",
  "./wheels/ipywidgets-8.1.7-py3-none-any.whl",
  "./wheels/itsdangerous-2.2.0-py3-none-any.whl",
  "./wheels/jedi-0.19.2-py2.py3-none-any.whl",
  "./wheels/jinja2-3.1.6-py3-none-any.whl",
  "./wheels/jsonschema-4.25.1-py3-none-any.whl",
  "./wheels/jsonschema_specifications-2025.4.1-py3-none-any.whl",
  "./wheels/jupyterlab_widgets-3.0.15-py3-none-any.whl",
  "./wheels/jupyter_core-5.8.1-py3-none-any.whl",
  "./wheels/MarkupSafe-3.0.2-cp311-cp311-win_amd64.whl",
  "./wheels/matplotlib_inline-0.1.7-py3-none-any.whl",
  "./wheels/narwhals-2.2.0-py3-none-any.whl",
  "./wheels/nbformat-5.10.4-py3-none-any.whl",
  "./wheels/nest_asyncio-1.6.0-py3-none-any.whl",
  "./wheels/numpy-2.3.2-cp311-cp311-win_amd64.whl",
  "./wheels/open3d-0.19.0-cp311-cp311-win_amd64.whl",
  "./wheels/packaging-25.0-py3-none-any.whl",
  "./wheels/parso-0.8.5-py2.py3-none-any.whl",
  "./wheels/platformdirs-4.4.0-py3-none-any.whl",
  "./wheels/plotly-6.3.0-py3-none-any.whl",
  "./wheels/prompt_toolkit-3.0.52-py3-none-any.whl",
  "./wheels/pure_eval-0.2.3-py3-none-any.whl",
  "./wheels/pygments-2.19.2-py3-none-any.whl",
  "./wheels/pywin32-311-cp311-cp311-win_amd64.whl",
  "./wheels/referencing-0.36.2-py3-none-any.whl",
  "./wheels/requests-2.32.5-py3-none-any.whl",
  "./wheels/retrying-1.4.2-py3-none-any.whl",
  "./wheels/rpds_py-0.27.1-cp311-cp311-win_amd64.whl",
  "./wheels/setuptools-80.9.0-py3-none-any.whl",
  "./wheels/stack_data-0.6.3-py3-none-any.whl",
  "./wheels/traitlets-5.14.3-py3-none-any.whl",
  "./wheels/typing_extensions-4.15.0-py3-none-any.whl",
  "./wheels/urllib3-2.5.0-py3-none-any.whl",
  "./wheels/wcwidth-0.2.13-py2.py3-none-any.whl",
  "./wheels/werkzeug-3.1.3-py3-none-any.whl",
  "./wheels/widgetsnbextension-4.0.14-py3-none-any.whl",
  "./wheels/zipp-3.23.0-py3-none-any.whl",
]

[dependencies]
python = ["numpy>=1.24"]

# Packaged files
[build]
paths = [
  "__init__.py",
  "ps1_decimator",
  "icons/icon.png",
  "README.md",
  "LICENSE",
]