schema_version = "1.0.0"

id = "ps1_decimator"
name = "PS1 Decimator"
version = "0.1.0"
type = "add-on"
tagline = "Stylized low-poly decimation + UV pixelation for PS1 aesthetics"
maintainer = "Hamada Gasmallah"

blender_version_min = "4.2.0"

license = ['SPDX:GPL-3.0-or-later']

# Optional but nice:
tags = ["Modeling", "Mesh"]
platforms = ["windows-x64"]

# Minimal wheel set required by the add-on at runtime.
wheels = []

[dependencies]
python = ["numpy>=1.26"]

# Packaged files
[build]
paths = [
  "__init__.py",
  "ps1d",
  "icons/icon.png",
  "README.md",
  "LICENSE"
]
